# Build all images and run all containers
# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: '3.8'
services:

  geoblacklight_db:
    container_name: geoblacklight_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${MYSQL_PORT}
      # Where our data will be persisted
    volumes:
      - './db-data:/var/lib/mysql'

  geoblacklight_web:
    container_name: geoblacklight_web
    build:
      context: ./
      dockerfile: DockerfileLocal
    env_file: .env
    environment:
      RAILS_ENV: $RAILS_ENV
    volumes:
      # App files to work locally
      - './app:/home/app/webapp/app'
      # Logs
      - './log:/home/app/webapp/log'
      - './webapp.conf:/etc/nginx/sites-enabled/webapp.conf'
    tty: true
    ports:
      - "3001:3001"
    depends_on:
      - geoblacklight_db