version: '3'
services:

  geoblacklight_db:
    container_name: geoblacklight_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${MYSQL_PORT}
      # Where our data will be persisted
    volumes:
      - './db-data:/var/lib/mysql'

  geoblacklight_web:
    container_name: geoblacklight_web
    build:
      context: ./
      dockerfile: DockerfileLocal
    env_file: .env
    volumes:
      - '.:/home/appuser'
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - geoblacklight_db

  geoblacklight_solr:
    container_name: geoblacklight_solr
    image: solr:8.5.2
    ports:
      - "8983:8983"
    volumes:
      - './solr_data:/opt/solr/server/solr/mycores'
      - './solr/conf:/var/solr/data/blacklight-core'
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - development
    depends_on:
      - geoblacklight_db
