name: Rails tests
on: [push]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: geo_harvard_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD:
        ports:
          - "3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      # - name: Verify MySQL connection from host
      #   run: |
      #     sudo apt-get install -y mysql-client libmysqlclient-dev
      #     mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
      #     mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot mysql
      - name: Fix bundler
        run: gem install bundler:2.2.11
      - name: Bundle installer
        run: bundle install
      - name: Start db?
        run: sudo service mysql start
      - name: create db
        run: rails db:create
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          RAILS_ENV: test
      - name: migrate db
        run: rails db:migrate
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
      - name: Run tests
        run: bundle exec rspec
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

